[package]
name = "terramask-py"
description = "Python bindings for terramask"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_terramask"
crate-type = ["cdylib"]

[dependencies]
terramask = { path = "../terramask" }
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py310"] }
